export const RECEIVE_ALLPRODUCTS = "RECEIVE_ALLPRODUCTS";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const RECEIVE_SINGLE_PRODUCT = "RECEIVE_SINGLE_PRODUCT";
export const ADD_CART = "ADD_CART";
export const CHECKOUT_CART = "CHECKOUT_CART";
export const SET_SEARCH = "SET_SEARCH"
